legacyDaemonsetAPI: false
compatWithCPUManager: false
migStrategy: none

nameOverride: ""
fullnameOverride: ""

namespace: kube-system

imagePullSecrets: []
image:
  repository: nvidia/k8s-device-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: {}

nodeSelector: {}

affinity: {}

tolerations:
  # This toleration is deprecated. Kept here for backward compatibility
  # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
